name: topflashcards
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  connectivity_plus: ^3.0.4
  firebase_auth: ^4.4.2
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  build_runner: ^2.3.3
  
  flutter_lints: ^2.0.0

flutter:  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
